### ISSUE TITLE
服务器存储空间100%后，ledis无法启动：index out of range

### ISSUE THREAD

**Issue by ArcherJiang** [ledisdb/ledisdb#256]
首先发现存储100%后，发现ledis进程丢失。
清理空间后，再次启动ledis，第一次报如下提示：
```
# ledis-server -config=/etc/ledis.conf

[2016/10/17 11:15:02] file_table.go:65 [Error] check 5 error: data file /xvdb/data/ledisdb/rpl/ldb/00000005.data invalid magic data "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", try to repair
[2016/10/17 11:15:02] file_table.go:230 [Error] /xvdb/data/ledisdb/rpl/ldb/00000005.data may lost logs from 15863881, invalid log 0
panic: runtime error: index out of range

goroutine 13 [running]:
github.com/siddontang/ledisdb/store/leveldb.(_WriteBatch).Delete(0xc82040ad20, 0xc820086738, 0x0, 0x3f)
        /xvdb/ledisdb/src/github.com/siddontang/ledisdb/store/leveldb/batch.go:58 +0x49
github.com/siddontang/ledisdb/store.(_WriteBatch).Delete(0xc82040c080, 0xc820086738, 0x0, 0x3f)
```
...
后面尝试再启动（中间无其它操作）
```
# ledis-server -config=/etc/ledis.conf

panic: runtime error: index out of range

goroutine 13 [running]:
github.com/siddontang/ledisdb/store/leveldb.(_WriteBatch).Delete(0xc8201a4b80, 0xc820086738, 0x0, 0x3f)
        /xvdb/ledisdb/src/github.com/siddontang/ledisdb/store/leveldb/batch.go:58 +0x49
github.com/siddontang/ledisdb/store.(_WriteBatch).Delete(0xc82004df00, 0xc820086738, 0x0, 0x3f)
        /xvdb/ledisdb/src/github.com/siddontang/ledisdb/store/writebatch.go:33 +0x5c
```

请问怎么解决

**Comment by lunny** [comment]
Could this problem be fixed by `ledis repair`? @siddontang
