### ISSUE TITLE
leveldb中的cgo错误

### ISSUE THREAD

**Issue by icexin** [ledisdb/ledisdb#267]
go版本1.6.3

发生了 `cgo argument has Go pointer to Go pointer`错误，错误堆栈如下：

```
[2016/12/14 15:55:35] client_resp.go:101 [Fatal] client run panic goroutine 53 [running]:
github.com/siddontang/ledisdb/server.(*respClient).run.func1(0xc8205db770)
	/home/vagrant/go/src/github.com/siddontang/ledisdb/server/client_resp.go:98 +0xb9
panic(0xb4d260, 0xc820295090)
	/home/vagrant/local/go/src/runtime/panic.go:443 +0x4e9
github.com/siddontang/ledisdb/store/leveldb._cgoCheckPointer0(0xa3a500, 0xc82028cc00, 0x0, 0x0, 0x0, 0x9f80a0)
	github.com/siddontang/ledisdb/store/leveldb/_obj/_cgo_gotypes.go:98 +0x4d
github.com/siddontang/ledisdb/store/leveldb.(*WriteBatch).Data(0xc820291ca0, 0x0, 0x0, 0x0)
	/home/vagrant/go/src/github.com/siddontang/ledisdb/store/leveldb/batch.go:101 +0xdc
github.com/siddontang/ledisdb/store.(*WriteBatch).BatchData(0xc82028cbc0, 0x6c0008c0)
	/home/vagrant/go/src/github.com/siddontang/ledisdb/store/writebatch.go:65 +0x41
github.com/siddontang/ledisdb/store.(*WriteBatch).Data(0xc82028cbc0, 0x0, 0x0, 0x0)
	/home/vagrant/go/src/github.com/siddontang/ledisdb/store/writebatch.go:75 +0x32
github.com/siddontang/ledisdb/ledis.(*Ledis).handleCommit(0xc8200f2300, 0x7f02ce083488, 0xc82028cbc0, 0x7f02ce0834b0, 0xc82028cbc0, 0x0, 0x0)
	/home/vagrant/go/src/github.com/siddontang/ledisdb/ledis/batch.go:108 +0x92
github.com/siddontang/ledisdb/ledis.(*batch).Commit(0xc820291cc0, 0x0, 0x0)
	/home/vagrant/go/src/github.com/siddontang/ledisdb/ledis/batch.go:26 +0xce
github.com/siddontang/ledisdb/ledis.(*DB).MSet(0xc820244080, 0xc8204d6000, 0x32c, 0x32c, 0x0, 0x0)
	/home/vagrant/go/src/github.com/siddontang/ledisdb/ledis/t_kv.go:269 +0x509
github.com/siddontang/ledisdb/server.msetCommand(0xc82025c160, 0x0, 0x0)
	/home/vagrant/go/src/github.com/siddontang/ledisdb/server/cmd_kv.go:219 +0x1df
github.com/siddontang/ledisdb/server.(*client).perform(0xc82025c160)
	/home/vagrant/go/src/github.com/siddontang/ledisdb/server/client.go:131 +0x325
github.com/siddontang/ledisdb/server.(*respClient).handleRequest(0xc8205db770, 0xc8204ca000, 0x659, 0x659, 0x0, 0x0)
	/home/vagrant/go/src/github.com/siddontang/ledisdb/server/client_resp.go:185 +0x4b1
github.com/siddontang/ledisdb/server.(*respClient).run(0xc8205db770)
	/home/vagrant/go/src/github.com/siddontang/ledisdb/server/client_resp.go:139 +0x24d
created by github.com/siddontang/ledisdb/server.newClientRESP
	/home/vagrant/go/src/github.com/siddontang/ledisdb/server/client_resp.go:91 +0x47b
:runtime error: cgo argument has Go pointer to Go pointer
```

**Comment by siddontang** [comment]
seem that I must upgrade go version and all dependences.
I will do it later if I have time.

**Comment by frankxieke** [comment]
export GODEBUG=cgocheck=0 @icexin
