### ISSUE TITLE
Crash in repair

### ISSUE THREAD

**Issue by mstory21** [ledisdb/ledisdb#340]
I'm getting this crash occasionally at boot.  Looks like when the replication log needs repaired.  Are these recommended settings to reduce replication log corruption?

```
github.com/siddontang/ledisdb/rpl.(*tableReader).repair(0xc42025b420, 0x21, 0xc42016b9f0)
        /home/cgp/repositories/cgp/thirdparty/src/go/src/github.com/siddontang/ledisdb/rpl/file_table.go:241 +0x31d
github.com/siddontang/ledisdb/rpl.newTableReader(0xc4201f6e40, 0x2f, 0x1a, 0x1, 0xc42016baf8, 0x1, 0x1)
        /home/cgp/repositories/cgp/thirdparty/src/go/src/github.com/siddontang/ledisdb/rpl/file_table.go:67 +0x204
github.com/siddontang/ledisdb/rpl.(*FileStore).load(0xc42025a8c0, 0x2f, 0xc4000001ed)
        /home/cgp/repositories/cgp/thirdparty/src/go/src/github.com/siddontang/ledisdb/rpl/file_store.go:340 +0x21c
github.com/siddontang/ledisdb/rpl.NewFileStore(0xc4201f6e40, 0x2f, 0xc420204000, 0xc4201f6e40, 0x2f, 0x0)
        /home/cgp/repositories/cgp/thirdparty/src/go/src/github.com/siddontang/ledisdb/rpl/file_store.go:85 +0x129
github.com/siddontang/ledisdb/rpl.NewReplication(0xc420204000, 0xc42015a690, 0x0, 0x0)
        /home/cgp/repositories/cgp/thirdparty/src/go/src/github.com/siddontang/ledisdb/rpl/rpl.go:62 +0x1dc
github.com/siddontang/ledisdb/ledis.Open(0xc420204000, 0xc42013dce0, 0x0, 0x0)
        /home/cgp/repositories/cgp/thirdparty/src/go/src/github.com/siddontang/ledisdb/ledis/ledis.go:74 +0x2e4
github.com/siddontang/ledisdb/server.NewApp(0xc420204000, 0x17, 0x7fffbc8ece25, 0x17)
        /home/cgp/repositories/cgp/thirdparty/src/go/src/github.com/siddontang/ledisdb/server/app.go:174 +0x3eb
main.main()
        /home/cgp/repositories/cgp/thirdparty/src/go/src/github.com/siddontang/ledisdb/cmd/ledis-server/main.go:92 +0x5c1
```

**Comment by mstory21** [comment]
Currently using mmap, sync every second, store type of file.

**Comment by siddontang** [comment]
Thanks, @mstory21 

I must re-browse whole codes to figure it out, maybe I will refactor all soon.

**Comment by EdKung** [comment]
Same problem here. 
In my case, services which manipulate dbs is stopped first for caution.
However, db crashed after normally restart the ledis-server.
Any recommendations to hard fix by truncating some logs or other possible ways? 
Thanks.

```
[2018/05/23 02:17:07] file_table.go:65 [Error] check 38 error: invalid log table, first 16214177, last 2025978305930216789, and log num 7127, try to repair
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7ce4ed]

goroutine 1 [running]:
github.com/siddontang/ledisdb/rpl.(*tableReader).repair(0xc4202581c0, 0x21, 0xc4201199f0)
	/home/edkung/ledisdb/src/github.com/siddontang/ledisdb/rpl/file_table.go:241 +0x31d
github.com/siddontang/ledisdb/rpl.newTableReader(0xc4201cab70, 0x22, 0x26, 0x1, 0xc420119af8, 0x1, 0x1)
	/home/edkung/ledisdb/src/github.com/siddontang/ledisdb/rpl/file_table.go:67 +0x204
github.com/siddontang/ledisdb/rpl.(*FileStore).load(0xc42023dab0, 0x22, 0xc4000001ed)
	/home/edkung/ledisdb/src/github.com/siddontang/ledisdb/rpl/file_store.go:340 +0x21c
github.com/siddontang/ledisdb/rpl.NewFileStore(0xc4201cab70, 0x22, 0xc4201ec000, 0xc4201cab70, 0x22, 0x0)
	/home/edkung/ledisdb/src/github.com/siddontang/ledisdb/rpl/file_store.go:85 +0x129
github.com/siddontang/ledisdb/rpl.NewReplication(0xc4201ec000, 0xc4201cc280, 0x0, 0x0)
	/home/edkung/ledisdb/src/github.com/siddontang/ledisdb/rpl/rpl.go:62 +0x1dc
github.com/siddontang/ledisdb/ledis.Open(0xc4201ec000, 0xc4201c6ba0, 0x0, 0x0)
	/home/edkung/ledisdb/src/github.com/siddontang/ledisdb/ledis/ledis.go:76 +0x2e4
github.com/siddontang/ledisdb/server.NewApp(0xc4201ec000, 0x16, 0x7ffe593c48ec, 0x16)
	/home/edkung/ledisdb/src/github.com/siddontang/ledisdb/server/app.go:174 +0x3eb
main.main()
	/home/edkung/ledisdb/src/github.com/siddontang/ledisdb/cmd/ledis-server/main.go:92 +0x5c1
```
